package com.developerev.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Stores the aggregate result of a full project AI review.
 * One row per CodeProject after the async pipeline completes.
 */
@Entity
@Table(name = "project_analysis")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ProjectAnalysis {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** FK to code_projects.id */
    @Column(nullable = false)
    private Long projectId;

    /**
     * JSON array of architecture issue descriptions detected by
     * ArchitectureAnalyzerService.
     * Example: ["Controller directly accesses repository", "Missing service layer"]
     */
    @Column(columnDefinition = "TEXT")
    private String architectureIssues;

    /**
     * JSON array of security issue descriptions detected by
     * SecurityAnalyzerService.
     * Example: ["Open CORS configuration", "Hardcoded password found in
     * DatabaseConfig.java"]
     */
    @Column(columnDefinition = "TEXT")
    private String securityIssues;

    /**
     * Human-readable project summary generated by AI.
     */
    @Column(columnDefinition = "TEXT")
    private String summary;

    /** Aggregate bug count across all reviewed files. */
    @Builder.Default
    private int totalBugs = 0;

    /** Aggregate security issue count across all reviewed files. */
    @Builder.Default
    private int totalSecurity = 0;

    /** Aggregate performance issue count across all reviewed files. */
    @Builder.Default
    private int totalPerformance = 0;

    /** Number of architecture-level issues detected. */
    @Builder.Default
    private int totalArchitecture = 0;

    private LocalDateTime createdAt;

    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
    }
}
